Updated npm version and fixed security vulnerabilities for some packages
JincorTech/backend-token-wallets pull request #65
Opened 2018-06-05 04:28 UTC by ddevilbb

2018-06-05 08:45 UTC, hlogeon approved these changes

2018-06-05 11:32 UTC, hlogeon requested changes
package-lock.json recreated? Unacceptable

2018-06-05 17:39 UTC, 01dr requested changes
Correct way:
`npm remove express-jwt` - remove dependency from package and package-lock. after that npm automatically regenerate package-lock tree without bump another deps
`npm install express-jwt` - install latest version
`npm install express-jwt@2.2.2` - specify version to install

2018-06-06 16:45 UTC, hlogeon approved these changes

2018-06-07 06:50 UTC, 01dr approved these changes

2018-06-07 12:33 UTC, merged